### ISSUE TITLE
SW 0.10.9 / GW 1.0.6 Unable to control Greenwave powernodes; deadlock at ProcessSendData?

### ISSUE THREAD

**Issue by TedTolboom** [athombv/com.greenwavesystems#18] opened 2016-11-10 18:23 UTC
Possibly linked to #17 but I don't know if the powernodes in that issues were blinking to indicate loss of connection or not (my case)

Homey Firmware v0.10.9
Greenwave App v1.0.6

Since the Homey and or Greenwave app update to above version, I am unable to switch on lights connected to the powernodes after ~ half a day. PTP resolves the issue for again half a day.

Before, Homey and it's 3 Powernode 6 and 1 Powernode 1 were operating for days / week stable without loosing connection. Several switches are triggered by flows based on light intensity and montion data from 2 Z-wave sensors.

Observations:
1) Z-wave network is still operational; motion sensor data is still received and the KAKU switches are acting upon it
2) Powernodes led's are not blinking to indicate that it has lost its connection to Homey
3) Switching on e.g. the TV connected to the powernode, almost instantly shows the change in energy, indicating that Homey is stil able to receive data from the powernode; supporting 2)
4) No apps crashed
5) Z-wave status indicates that it is trying to send data (continuous): 

<img width="811" alt="schermafbeelding 2016-11-10 om 19 15 19" src="https://cloud.githubusercontent.com/assets/17163431/20188681/148f2f96-a77a-11e6-8ae0-66cd2389abd7.png">

LOG: 566070DA83

<img width="932" alt="schermafbeelding 2016-11-10 om 19 14 25" src="https://cloud.githubusercontent.com/assets/17163431/20188703/29c92e16-a77a-11e6-8b4c-6febd8b17486.png">

@Eternity-again can you check if you also loose connection while Z-wave is trying to ProcessSendData?

@RobinBol First guess would be the Greenwave app... but it does not correspond to the changelog
@WeeJeWel possible more generic Z-wave issue originating from Homey SW update?

**Comment by mike9011** [comment] 2016-11-14 13:10
Same issue here... I don't have any greenwave devices connected.
Reboot didn't solved the issue. Not able to control any z-wave device anymore.

![zwave](https://cloud.githubusercontent.com/assets/18025163/20265915/ec754d90-aa73-11e6-8f5d-461df05f6b46.PNG)

**Comment by TedTolboom** [comment] 2016-11-16 20:44
Possible rootcause for my issue, see https://github.com/athombv/com.fibaro/issues/70

Hypothesis for this Github issue is that due to the erratic data logging of the fibaro motion sensor, triggering directly a switch on (or off) command on a lamp connected to the powernode is trying to send too often a on command creating a deadlock...

My flows have been updated to only send a on command if the lamps are switched off (and vv)

<img width="1133" alt="schermafbeelding 2016-11-16 om 21 41 39" src="https://cloud.githubusercontent.com/assets/17163431/20364946/7f9f4422-ac45-11e6-9cba-30fc769cecc8.png">

I will check the next days to see if this is solving my issue

**Comment by jghaanstra** [comment] 2016-11-19 21:34
I can confirm this issue. This happens to me about once or twice a week.

I do have Greenwave devices but I cant tell for sure it's related to these devices specifically. @mike9011 seems to confirm it can be caused by other zwave devices as well so it seems to be a generic deadlock issue in sending on/off zwave commands.

As mentioned, recieving energy data of the zwave sockets is not effected by the issue. But the motion alarm of my Fibaro sensor is not cancelled anymore when this issue occurs.

Only fix for now is a Homey reboot.

**Comment by SergeRegoor** [comment] 2016-11-29 05:53
I can confirm this, too. Not only the Fibaro motion sensors behave erratically, but also my Danalock. For example, the Danalock would not respond to any z-wave command. Bluetooth commands work just fine. After disabling the Greenwave app (and a reboot of Homey), the Danalock and other devices work as expected again.

**Comment by RobinBol** [comment] 2016-12-07 12:34
Is the process send data lock still present on v1.0.3?

**Comment by jghaanstra** [comment] 2016-12-07 12:43
Yes it is, just experienced it again this morning. Does not seem to happen out of the blue that much anymore but I occured when I was fiddeling with creating new flows and pairing 433 devices. I seriously doubt it's completely related to the Greenwave devices but cant tell for sure.

**Comment by TedTolboom** [comment] 2016-12-07 13:42
Yes, still there...
Even this morning about 1.5 hours after a scheduled reboot... At this moment already restarting for the 3rd time (due to lock at ProcessSendData)...

I did install 2 additional PowerNode 1's at the pantry... possible at the edge of the range of Homey...
I don't know if they are being reached through the Z-wave network mesh...

My current network setup:
3x Powernode-6 (4-5m from Homey, direct line of sight)
2x Fibaro motion sensor non-plus (3 and 7m from homey, direct line of sight)
2x NEO Coolcam power plug (4 and 9m from homey)
2x Powernode-1 (~12m from Homey, in pantry)

I will remove these powernode-1's this evening to see if it is becoming more stable again.

I will remove these powernode-1's to

**Comment by TedTolboom** [comment] 2016-12-07 14:29
I couldn't resist to check further...

I do notice that on both powernode-1's (added after 1.0.3 update), there is a huge data traffic on energy readings...
> Wed Dec 07 2016 15:07:02 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:11 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:13 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:20 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:22 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:34 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:37 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:38 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:40 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:42 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:44 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:47 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:49 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:07:55 GMT+0100 (CET),0
> Wed Dec 07 2016 15:07:59 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:08:10 GMT+0100 (CET),0
> Wed Dec 07 2016 15:08:11 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:08:17 GMT+0100 (CET),0
> Wed Dec 07 2016 15:08:23 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:08:37 GMT+0100 (CET),0
> Wed Dec 07 2016 15:08:38 GMT+0100 (CET),0.1
> Wed Dec 07 2016 15:08:43 GMT+0100 (CET),0
> Wed Dec 07 2016 15:08:46 GMT+0100 (CET),0.1

Also here, I assume that Homey will only log data if different compared to the previous data point... to actual data frequency is expected to be higher than shown in the download of insights

Which is strange, since the polling interval is set at 300 seconds and updated after adding these devices... If both these devices are sending this amount of data / or Homey is polling more frequently... this could bring the Z-wave network down.

My other powernodes seem to be reporting on the specified interval

It does look similar compared to the issue I reported on the [Fibaro Motion sensor](https://github.com/athombv/com.fibaro/issues/70)...

**Comment by Eternity-again** [comment] 2016-12-07 17:27
Unfortunately I have to agree, after the update to experimental 1.0.3 the
green Led problem have increased in frequency. I need to reboot at least 3
times a day.




Op 7 dec. 2016 3:29 p.m. schreef "dT" <notifications@github.com>:

**Comment by TedTolboom** [comment] 2016-12-07 18:49
Something similar behaviour on another sub-node of a PN6 (set at polling interval 301 seconds):

Power (nicely reporting in ~300 seconds interval):

> Tue Dec 06 2016 19:26:31 GMT+0100 (CET),1.55
> Tue Dec 06 2016 19:36:30 GMT+0100 (CET),1.56
> Tue Dec 06 2016 19:41:33 GMT+0100 (CET),1.57
> Tue Dec 06 2016 19:51:30 GMT+0100 (CET),1.58
> Wed Dec 07 2016 00:46:34 GMT+0100 (CET),1.58
> Wed Dec 07 2016 09:48:45 GMT+0100 (CET),1.6
> Wed Dec 07 2016 14:57:11 GMT+0100 (CET),1.64
> Wed Dec 07 2016 15:12:13 GMT+0100 (CET),1.65
> Wed Dec 07 2016 15:17:13 GMT+0100 (CET),1.66
> Wed Dec 07 2016 15:37:14 GMT+0100 (CET),1.67
> Wed Dec 07 2016 16:07:13 GMT+0100 (CET),1.69
> Wed Dec 07 2016 16:12:14 GMT+0100 (CET),1.7
> Wed Dec 07 2016 16:37:13 GMT+0100 (CET),1.72
> Wed Dec 07 2016 19:27:53 GMT+0100 (CET),1.81
> 

Whereas Energie (of same node, with same polling interval), is showing strange data:

> Wed Dec 07 2016 19:27:53 GMT+0100 (CET),63.1
> Wed Dec 07 2016 19:28:03 GMT+0100 (CET),5
> Wed Dec 07 2016 19:28:30 GMT+0100 (CET),3.9
> Wed Dec 07 2016 19:28:39 GMT+0100 (CET),5.3
> Wed Dec 07 2016 19:28:48 GMT+0100 (CET),6.6
> Wed Dec 07 2016 19:28:57 GMT+0100 (CET),5.5
> Wed Dec 07 2016 19:29:06 GMT+0100 (CET),6.2
> Wed Dec 07 2016 19:29:15 GMT+0100 (CET),5
> Wed Dec 07 2016 19:29:33 GMT+0100 (CET),6.5
> Wed Dec 07 2016 19:29:43 GMT+0100 (CET),5.6
> Wed Dec 07 2016 19:30:28 GMT+0100 (CET),4.7
> Wed Dec 07 2016 19:30:32 GMT+0100 (CET),59.3
> Wed Dec 07 2016 19:30:36 GMT+0100 (CET),5.2
> Wed Dec 07 2016 19:30:50 GMT+0100 (CET),74.8
> Wed Dec 07 2016 19:31:12 GMT+0100 (CET),6.5
> Wed Dec 07 2016 19:31:21 GMT+0100 (CET),5.3
> Wed Dec 07 2016 19:31:30 GMT+0100 (CET),4.5
> Wed Dec 07 2016 19:31:39 GMT+0100 (CET),6.3
> Wed Dec 07 2016 19:31:48 GMT+0100 (CET),5.7
> Wed Dec 07 2016 19:32:33 GMT+0100 (CET),5
> Wed Dec 07 2016 19:32:51 GMT+0100 (CET),4.1
> Wed Dec 07 2016 19:33:00 GMT+0100 (CET),5.4

The TV is currently in use so I would expect an energy level above 50W... I don't understand the intermediate reports (every 9 seconds)..

Anyone similar results?

In all three cases, settings (polling interval) were changed recently (SW1.0+) or devices have been added on SW v1.0.3..  

Just updated a 4th sub-node.. see if I'm able to reproduce.

**Comment by jghaanstra** [comment] 2016-12-09 18:14
I can confirm this issue has increased with 1.0.3. On 1.0.2 I hardly had issues with zwave chip hanging on processSendData. Now it happes a couple of times per day. Only thing that has changed is that I added two NEO Coolcam products (sensor and wallplug).

Not seeying any strange energy reportings in the raw data of insights.

My current zwave setup:
- 2 powernode-6
- 2 powernode-1
- Fibaro motion sensor zwave+
- Fibaro wall plug
- NEO Coolcam sensor
- Neo Wall Plug
- Duwi / Zwave-me single swithc

I have send a log: 0E40B8F662

**Comment by TedTolboom** [comment] 2016-12-10 21:39
Just re-paired my troublesome Powernode 6 and 2x Powernode 1's...
I also noticed that with the latest GW app, the keep alive time is set at 255 for the main nodes... but ALSO for the sub-nodes...

I always was told that you should not touch / change the sub-nodes keep alive time... if I recall correctly, previously it was set at 2...

**Comment by Eternity-again** [comment] 2016-12-10 22:11
How are they doing now?

Op 10 dec. 2016 10:39 p.m. schreef "dT" <notifications@github.com>:

**Comment by TedTolboom** [comment] 2016-12-10 22:15
See my edited post on GitHub (does not trigger an additonal notification mail)... 
same issue with the same sub-node on the power-node 6... keeps sending more data compared to polling interval... I will swap 2 devices with their sockets / sub-nodes to see if it is device specific behavior or not.

**Comment by TedTolboom** [comment] 2016-12-10 22:33
Nope... swapping devices did not solve it. Still energy data every 9 seconds while a PS4 is connected instead of a TV.

In addition, my power node 1's are blinking again... Eventhough they are at a closer distance compared to the PN6's..

**Comment by TedTolboom** [comment] 2016-12-12 21:51
Most likely found the issue....

Based on the default settings of the GW app, setting association group 3 to Homey's ID will enable the power node device to push reports to Homey. Without changes to parameter 0, the power node device will push report every 10% power change.

association group 3: Power value change
parameter 0: Power change required to send a notification, in % from 1 to 100, default 10

After removing Homey's ID out of association group 3, meter reports are no longer being pushed to Homey, but only pulled via the polling interval. See below example
<img width="989" alt="schermafbeelding 2016-12-12 om 21 40 47" src="https://cloud.githubusercontent.com/assets/17163431/21117974/36f2cc72-c0bc-11e6-92b6-a8bf304571c1.png">

Pull request to temporarery remove association group 3 (and enable setting the polling interval of PN1 to 0): #20 ... 
superseded by @jghaanstra pull request #21 to implement parameter 0 into the device parameters:
<img width="600" alt="schermafbeelding 2016-12-12 om 22 49 29" src="https://cloud.githubusercontent.com/assets/17163431/21118246/45585506-c0bd-11e6-822f-655996e702dd.png">
the more elegant solution.... off course

Updated app installed... let's see what stability improvements this will achieve...

**Comment by TedTolboom** [comment] 2016-12-12 22:41
@WeeJeWel @RobinBol 
Next to the Greenwave devices also other Z-wave devices have the power meter push setting set at default at relatively low values. 
Greenwave at 10% power change, Neo at 30% power change and Aeotec at only 5% power change.

As example my Neo powerplug logging (at default settings):

> Mon Dec 12 2016 21:39:12 GMT+0100 (CET),0.33
> Mon Dec 12 2016 21:39:20 GMT+0100 (CET),0.29
> Mon Dec 12 2016 21:39:28 GMT+0100 (CET),0.34
> Mon Dec 12 2016 21:39:50 GMT+0100 (CET),0.32
> Mon Dec 12 2016 21:40:06 GMT+0100 (CET),0.33
> Mon Dec 12 2016 21:40:22 GMT+0100 (CET),0.28
> Mon Dec 12 2016 21:40:32 GMT+0100 (CET),0.33
> Mon Dec 12 2016 21:40:44 GMT+0100 (CET),0.37
> Mon Dec 12 2016 21:40:52 GMT+0100 (CET),0.34
> Mon Dec 12 2016 21:40:58 GMT+0100 (CET),0.37
> Mon Dec 12 2016 21:42:08 GMT+0100 (CET),0.35
> Mon Dec 12 2016 21:42:26 GMT+0100 (CET),0.37
> Mon Dec 12 2016 21:43:00 GMT+0100 (CET),0.35
> Mon Dec 12 2016 21:43:06 GMT+0100 (CET),0.37
> Mon Dec 12 2016 21:43:16 GMT+0100 (CET),0.32
> Mon Dec 12 2016 21:43:26 GMT+0100 (CET),0.36
> Mon Dec 12 2016 21:44:06 GMT+0100 (CET),0.38
> Mon Dec 12 2016 21:44:14 GMT+0100 (CET),0.36
> Mon Dec 12 2016 21:44:50 GMT+0100 (CET),0.39
> Mon Dec 12 2016 21:44:58 GMT+0100 (CET),0.3
> Mon Dec 12 2016 21:45:04 GMT+0100 (CET),0.35
> Mon Dec 12 2016 21:55:06 GMT+0100 (CET),0.3
> Mon Dec 12 2016 21:55:12 GMT+0100 (CET),0.33
> Mon Dec 12 2016 21:56:14 GMT+0100 (CET),0.26
> Mon Dec 12 2016 21:56:22 GMT+0100 (CET),0.37

Considering the suspected impact of these push-reports on the stability of the Z-wave network (I only had 4-5 devices that showed this behaivior blocking my Z-wave network), I would recommend to check the Z-wave apps to include a higher app default value for this particular setting.

**Comment by JPe2** [comment] 2016-12-13 22:16
_"hint": {
						"en": "The amount of minutes without contact between controller and device before the device starts blinking green.",
						"nl": "Aantal minuten zonder contact tussen controller en apparaat voordat het apparaat groen gaat knipperen."_
Shouldn't this be seconds in stead of minutes?

**Comment by jghaanstra** [comment] 2016-12-13 22:18
Nope, it's minutes ... ;-)

**Comment by TedTolboom** [comment] 2016-12-17 23:20
1 day after the update to SW v1.0.4 and setting the devices to the standard polling intervals (yet with higher power change reporting parameter (parameter-0 at 80%), I did not observe any lockups.

I will (stress) test the next days with standard settings; polling at 300 seconds and parameter-0 at 10% with 4x PN-6, 2x PN-1 and 3x NEO power plug

**Comment by RobinBol** [comment] 2016-12-19 14:16
Process Send Data lockup is fixed in Homey client firmware, will close this issue for now.

**Closed by RobinBol** 2016-12-19 14:16 UTC
